export default {
	GENERADA: 1,
    REMITIDA: 2,
    ACEPTADA: 3,
    RECHAZADA: 4,
    CIERRE_BOLSA: 5,
    ASIGNADA: 6,
    REASIGNADA: 7,
    DILIGENCIADA: 8,
    EXTRAVIADA: 9,
    DEVUELTA: 10,
    ANULADA: 14
 }